export interface User {
  id: string;
  name: string;
  faceDescription: string; // Generated by Gemini as a "semantic embedding"
  registeredAt: string;
  lastSeen?: string;
  preferences?: UserPreferences;
  interactionCount?: number;
}

export interface LogEntry {
  id: string;
  timestamp: string;
  type: 'INFO' | 'SUCCESS' | 'WARNING' | 'ERROR' | 'RECOGNITION';
  message: string;
  details?: string;
}

export enum AppState {
  IDLE = 'IDLE',
  REGISTRATION = 'REGISTRATION',
  RECOGNITION = 'RECOGNITION',
  DASHBOARD = 'DASHBOARD'
}

export interface BoundingBox {
  ymin: number;
  xmin: number;
  ymax: number;
  xmax: number;
}

export interface DetectionResult {
  faceDetected: boolean;
  multipleFaces: boolean;
  description?: string;
  qualityCheckPassed: boolean;
  error?: string;
  boundingBox?: BoundingBox;
}

export interface RecognitionResult {
  matchFound: boolean;
  userId?: string;
  confidence: number;
  greeting?: string;
  error?: string;
  boundingBox?: BoundingBox;
}

// === New Types for Advanced Features ===

export interface Emotion {
  primary: 'happy' | 'sad' | 'angry' | 'surprised' | 'neutral' | 'fearful' | 'disgusted';
  confidence: number;
  sentiment: 'positive' | 'negative' | 'neutral';
  sentimentScore: number; // -1 to 1
  timestamp: string;
}

export interface ConversationMessage {
  id: string;
  userId?: string; // null for system messages
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  isVoice?: boolean;
}

export interface VoiceCommand {
  command: string;
  transcript: string;
  confidence: number;
  timestamp: string;
  executed: boolean;
  error?: string;
}

export interface SecurityCheck {
  livenessDetected: boolean;
  livenessScore: number; // 0-1
  spoofDetected: boolean;
  spoofConfidence: number; // 0-1
  details: {
    blinkDetected?: boolean;
    movementDetected?: boolean;
    depthAnalysis?: 'pass' | 'fail' | 'uncertain';
    screenDetection?: boolean;
    printDetection?: boolean;
  };
  timestamp: string;
  passed: boolean;
}

export interface UserPreferences {
  userId: string;
  voiceEnabled: boolean;
  voiceName?: string; // TTS voice preference
  conversationHistory: boolean;
  emotionTracking: boolean;
  privacyMode: boolean;
  lastUpdated: string;
}

export interface InteractionContext {
  userId: string;
  lastSeen: string;
  conversationHistory: ConversationMessage[];
  emotionHistory: Emotion[];
  preferences: UserPreferences;
  totalInteractions: number;
  averageMood: 'positive' | 'negative' | 'neutral';
}

export interface EmotionAnalysisResult {
  emotion: Emotion;
  error?: string;
}

export interface LivenessResult extends SecurityCheck {
  frameAnalysis: Array<{
    frameNumber: number;
    blinkDetected: boolean;
    movementScore: number;
  }>;
}