export interface User {
  id: string;
  name: string;
  faceDescription: string; // Generated by Gemini as a "semantic embedding"
  registeredAt: string;
}

export interface LogEntry {
  id: string;
  timestamp: string;
  type: 'INFO' | 'SUCCESS' | 'WARNING' | 'ERROR' | 'RECOGNITION';
  message: string;
  details?: string;
}

export enum AppState {
  IDLE = 'IDLE',
  REGISTRATION = 'REGISTRATION',
  RECOGNITION = 'RECOGNITION',
  DASHBOARD = 'DASHBOARD'
}

export interface BoundingBox {
  ymin: number;
  xmin: number;
  ymax: number;
  xmax: number;
}

export interface DetectionResult {
  faceDetected: boolean;
  multipleFaces: boolean;
  description?: string;
  qualityCheckPassed: boolean;
  error?: string;
  boundingBox?: BoundingBox;
}

export interface RecognitionResult {
  matchFound: boolean;
  userId?: string;
  confidence: number;
  greeting?: string;
  error?: string;
  boundingBox?: BoundingBox;
}